// ============================================================
//  PALABRAS PRESELECCIONADAS POR CATEGORIA
// ============================================================

export const presetPolitica = ['politica','gobierno','vito quiles','pedro sanchez','trump','putin','dictador','irene montero','pablo iglesias','perro sanchez','abascal','presidente','elecciones','votar','congreso','senado','ministro','partido popular','psoe','vox','parlamento','diputado','alcalde','socialista','constitucion','democracia','corrupcion','mocion','censura','impuesto','sanidad','pensiones','inmigracion'];

export const presetFutbol = ['penya','peña','penyo','bacana','merengue','culer','futbol','balon','laliga','champions','real madrid','barcelona','atletico','atleti','pateti','seleccion','mundial','eurocopa','entrenador','arbitro','penalti','estadio','aficion','futbolista','messi','ronaldo','neymar','mbappe','haaland','vinicius','bellingham','rodri','morata','pedri','gavi','valverde','ancelotti','guardiola','mourinho','zidane','cruyff','maradona','pele','beckham','buffon','neuer','lewandowski','benzema','modric','kroos','delantero','defensa','portero','mediocampista','despeje','corner','tarjeta roja','tarjeta amarilla','golazo','remate','asistencia','fuera de juego','offside','lesion','cantera','fichaje','traspaso','clasico','derbi'];

export const presetAnime = ['anime','manga','otaku','naruto','one piece','dragon ball','attack on titan','shingeki','kimetsu','demon slayer','jujutsu','kaisen','death note','sword art online','sao','my hero academia','boku no hero','fullmetal','alchemist','steins gate','evangelion','neon genesis','cowboy bebop','ghost in the shell','spirited away','totoro','ghibli','miyazaki','pokemon','digimon','sailor moon','berserk','vinland saga','chainsaw man','spy x family','konosuba','re zero','overlord','one punch man','mob psycho','hunter x hunter','hxh','code geass','fate','monogatari','madoka','made in abyss','haikyuu','kuroko','slam dunk','initial d','yugioh'];

export const presetVideojuegos = ['videojuego','gaming','ps5','ps4','xbox','nintendo','switch','pc','steam','epic games','playstation','xbox series','gamepass','minecraft','fortnite','call of duty','fifa','ea fc','gta','grand theft auto','red dead redemption','rdr2','the witcher','cyberpunk','elden ring','dark souls','bloodborne','sekiro','skyrim','fallout','elder scrolls','baldurs gate','divinity','league of legends','valorant','overwatch','counter strike','csgo','cs2','world of warcraft','final fantasy','zelda','super mario','metroid','god of war','last of us','uncharted','spiderman','horizon','assassins creed','far cry','resident evil','silent hill','metal gear solid','mass effect','bioshock','apex legends','pubg','rocket league','roblox'];

export const presetCripto = ['bitcoin','btc','ethereum','eth','crypto','cripto','blockchain','token','altcoin','solana','cardano','ripple','xrp','polkadot','avalanche','avax','polygon','matic','chainlink','litecoin','ltc','dogecoin','doge','shiba','shib','uniswap','binance','bnb','cosmos','near','stellar','xlm','monero','xmr','trx','defi','nft','web3','metaverso','mining','mineria','wallet','exchange','stablecoin','usdt','usdc','airdrop','staking','farming','yield','pool','swap','trading','trader','hold','hodl','pump','dump','bear market','bull market'];

export const preset18 = ['+18','+16','+17','oslafo','osfo','contenido sensible','ojosensibles','ojossensibles','ojo sensibles','ojos sensibles','nsfw','sexo','porno','xxx','desnudo','desnudos','desnuda','desnudas','tetas','teta','culo','polla','coño','follar','follais','paja','masturbacion','masturbais','pornografia','18+'];
